// Generated by scripts/build-brochure.mjs — do not edit by hand.

export type BrochurePage = {
  /** 1-based book page number */
  n: number;
  src: string;
  thumb: string;
  alt: string;
};

export const BROCHURE_PDF = "/brochure/velora-brochure.pdf";

export const BROCHURE_PAGES: BrochurePage[] = Array.from({ length: 24 }, (_, i) => {
  const n = i + 1;
  const id = String(n).padStart(2, "0");
  return {
    n,
    src: `/brochure/pages/page-${id}.webp`,
    thumb: `/brochure/thumbs/page-${id}.webp`,
    alt:
      n === 1
        ? "Velora brochure — front cover"
        : n === 24
          ? "Velora brochure — back cover"
          : `Velora brochure — page ${n}`,
  };
});
